"""Assemble the per-component K_d* error budget for Table 3.

Reads the canonical retrieval JSON and all five auxiliary-sensitivity
JSONs, combines them in quadrature, and writes the result to
results/kd_error_budget.json.

Required inputs (run their generating scripts first if missing):
    results/kd_retrieval_results.json            -- retrieve_kd.py
    results/borestem_sensitivity.json            -- compute_borestem_sensitivity.py
    results/stability_threshold_sensitivity.json -- compute_stability_threshold_sensitivity.py
    results/surface_bias_test.json               -- compute_surface_bias_test.py
    results/common_epoch_sensitivity.json        -- compute_common_epoch.py
    (no input file needed for sigma_Qb -- it is analytical from the
     K_d/Q_b degeneracy, with the published Q_b envelopes hard-coded
     below from Langseth (1976), Saito (2007), and Nagihara (2018).)

Output schema (kd_error_budget.json):
    {
      "A15": {
        "sigma_stat": float,         # bootstrap CI half-width
        "sigma_Qb":   float,         # K_d * (max(Q_b)-min(Q_b)) / (2*Q_b_nom)
        "sigma_zb":   float,         # half-range over the borestem-cut sweep
        "sigma_thr":  float,         # half-range over stability-threshold sweep
        "sigma_epoch": float,        # |common-1974 refit - certified| (one-sided)
        "sigma_A":    float,         # half-range over Bond-albedo sweep
        "sigma_chi":  float,         # Hayne 2017 chi sensitivity (constant)
        "sigma_H":    float,         # joint K_d-H fit sensitivity
        "sigma_Ks":   float,         # surface conductivity (constant)
        "sigma_rho":  float,         # bulk density (constant)
        "total_quadrature": float,   # sqrt(sum sigma_i^2)
        "median":  float,            # bootstrap median (mW/m/K)
        "ci95_lo": float,            # 95% lower bound (mW/m/K)
        "ci95_hi": float             # 95% upper bound (mW/m/K)
      },
      "A17": { ... same keys ... }
    }

Run with:
    python pipeline/compute/compute_error_budget.py
"""
from __future__ import annotations
import json
import pathlib

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "results"

# Published Q_b envelopes in mW m^-2 (Langseth 1976 / Saito 2007 / Nagihara 2018).
# The nominal comes from config.SITES (single source of truth; the hardcoded
# 16 here once went stale at 15 -- the 2026-06-30 straggler); only the
# literature envelope bounds are stated locally.
from lunar.config import SITES as _SITES
QB_ENVELOPES = {
    "A15": {"nominal": _SITES["A15"]["Q_BASAL"] * 1e3, "low": 14.0, "high": 25.0},
    "A17": {"nominal": _SITES["A17"]["Q_BASAL"] * 1e3, "low": 10.0, "high": 18.0},
}

# Fixed-input sensitivities (chi, H, K_s, rho) are re-retrievals at the
# perturbed inputs, generated by
# compute_fixed_input_sensitivities.py -> fixed_input_sensitivities.json.
# Run that script first if the file is missing.


def _half_range(values):
    """Half-range = (max - min) / 2 across a sensitivity sweep."""
    v = np.asarray(values, dtype=float)
    return float((v.max() - v.min()) / 2.0)


def main() -> int:
    print("Loading inputs...")
    kd = json.loads((OUT / "kd_retrieval_results.json").read_text())
    bs = json.loads((OUT / "borestem_sensitivity.json").read_text())
    th = json.loads((OUT / "stability_threshold_sensitivity.json").read_text())
    sb = json.loads((OUT / "surface_bias_test.json").read_text())
    fx = json.loads((OUT / "fixed_input_sensitivities.json").read_text())
    ce = json.loads((OUT / "common_epoch_sensitivity.json").read_text())

    budget = {}
    for site in ("A15", "A17"):
        bootstrap = kd[site]["bootstrap"]
        # sigma_stat = half-width of the bootstrap 16-84 percentile interval
        samples_mW = np.array(bootstrap["samples"]) * 1e3
        p16, p84 = np.percentile(samples_mW, [16, 84])
        sigma_stat = float((p84 - p16) / 2.0)

        # sigma_Qb from the DIRECT degeneracy map (audit F-9): half-range of
        # the measured K_d*(Q_b) over the published envelope. The old
        # analytical rule K_d*(alpha Qb) = alpha K_d* is a disproved model
        # of the degeneracy -- it UNDERSTATED A15 (whose direct response is
        # steeper than proportional) and even had the A17 direction wrong.
        # results/qb_degeneracy.json is written by compute_qb_degeneracy.py;
        # run it first if missing.
        from scipy.interpolate import PchipInterpolator
        env = QB_ENVELOPES[site]
        kd_nom_mW = kd[site]["kd_star"] * 1e3
        dg = json.loads((OUT / "qb_degeneracy.json").read_text())["sites"][site]
        f_kd = PchipInterpolator([r["qb_mW"] for r in dg],
                                 [r["kd_star_mW"] for r in dg])
        qq = np.linspace(env["low"], env["high"], 200)
        kd_env = f_kd(qq)
        sigma_Qb = float((kd_env.max() - kd_env.min()) / 2.0)
        qb_asym = (float(kd_env.max() - kd_nom_mW),
                   float(kd_env.min() - kd_nom_mW))   # (+up, -down) vs nominal

        # Sweep half-ranges.
        # sigma_zb uses only the physically defensible cuts {70, 80, 90} cm.
        # The 60-cm cut readmits a borestem-contaminated sensor at A17
        # (manuscript Sec. 3.2) and is a diagnostic, not an uncertainty.
        cuts = bs["cut_cm"]
        zb_vals = [v for c, v in zip(cuts, bs[site]) if c >= 70]
        sigma_zb = _half_range(zb_vals)
        sigma_thr = _half_range(th[site]["kd_star_mW"])
        # sigma_A over the +/-0.01 Bond-albedo envelope (the published
        # Vasavada 2012 lat-band scatter). Perturbations beyond ~0.01
        # push the deep-T(K_d) response into a non-monotonic regime
        # where the retrieval hops between RMSE branches, so larger
        # envelopes do not define a meaningful 1-sigma.
        dA = np.asarray(sb["delta_albedo"], dtype=float)
        kA = np.asarray(sb[site]["kd_star"], dtype=float)
        sigma_A = _half_range(kA[np.abs(dA) <= 0.0101])

        # Solver systematic: grid+dt convergence (halve dz0 to 1 mm @ 4% growth
        # and halve dt to 1800 s -> <=0.025) combined in quadrature with the
        # anchor-depth sensitivity (the converged K_d* spans 0.06 mW across
        # z0 = 0.45-0.70 m -> half-range ~0.03): sqrt(0.025^2 + 0.03^2) ~ 0.04.
        # NOTE the inner spin-up is now CONVERGED (EQ_N_INNER=90, flux closure
        # <0.5%); the old n_inner=12 biased K_d* HIGH by ~0.4 mW, but that was a
        # BIAS (now removed), NOT a 1-sigma. The reported K_d* sits within this
        # sigma of the closure->0 limit. Source: n_inner + z0 studies 2026-06-30.
        sigma_solver = 0.04

        # sigma_epoch: the A17 stability windows mix 1974-1977 epochs
        # aligned with depth; re-fitting every sensor at one shared 1974
        # window moves K_d* by this much (one-sided; manuscript
        # Sec. "consistency"). A15 is epoch-uniform already (<0.02).
        sigma_epoch = abs(ce[site]["common_1974"]["kd_star_mW"]
                          - ce[site]["certified"]["kd_star_mW"])

        # Quadrature total covers the statistical and measured-input
        # components that respond linearly across their envelopes.
        # chi and H are NOT totaled: they parameterize the Hayne
        # functional form itself, and re-retrieving at the Vasavada
        # chi = 1.48 normalisation drives the minimum outside the
        # physical sweep range at both sites -- K_d* is reported
        # conditional on the published form (chi = 2.7, H = 6 cm),
        # exactly as it is conditional on the published Q_b. Their
        # ranges are reported separately as conditionality terms.
        sigmas = {
            "sigma_stat": sigma_stat,
            "sigma_solver": sigma_solver,
            "sigma_Qb": sigma_Qb,
            "sigma_zb": sigma_zb,
            "sigma_thr": sigma_thr,
            "sigma_epoch": sigma_epoch,
            "sigma_A": sigma_A,
            "sigma_Ks": float(fx[site]["sigma_Ks"]),
            "sigma_rho": float(fx[site]["sigma_rho"]),
        }
        total = float(np.sqrt(sum(s ** 2 for s in sigmas.values())))
        sigmas["sigma_Qb_asymmetric_up_down"] = qb_asym   # not summed (report)
        sigmas["conditional_chi"] = float(fx[site]["sigma_chi"])
        sigmas["conditional_H"] = float(fx[site]["sigma_H"])
        sigmas["kd_at_chi_1p48"] = float(fx[site]["kd_at_chi_1p48"])

        budget[site] = {
            **sigmas,
            "total_quadrature": total,
            "median": float(np.median(samples_mW)),
            "ci95_lo": float(np.percentile(samples_mW, 2.5)),
            "ci95_hi": float(np.percentile(samples_mW, 97.5)),
        }

        print(f"\n  {site}:")
        for k, v in budget[site].items():
            print(f"    {k:<20} = {v}" if isinstance(v, (tuple, list))
                  else f"    {k:<20} = {v:.4f}")

    out_path = OUT / "kd_error_budget.json"
    out_path.write_text(json.dumps(budget, indent=2))
    print(f"\nSaved: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
