"""Assemble the per-component K_d* error budget for Table 3.

Reads the canonical retrieval JSON and all five auxiliary-sensitivity
JSONs, combines them in quadrature, and writes the result to
results/kd_error_budget.json.

Required inputs (run their generating scripts first if missing):
    results/kd_retrieval_results.json            -- retrieve_kd.py
    results/borestem_sensitivity.json            -- compute_borestem_sensitivity.py
    results/stability_threshold_sensitivity.json -- compute_stability_threshold_sensitivity.py
    results/surface_bias_test.json               -- compute_surface_bias_test.py
    results/albedo_sensitivity.json              -- compute_albedo_sensitivity.py
    results/fixed_input_sensitivities.json       -- compute_fixed_input_sensitivities.py
    results/qb_degeneracy.json                   -- compute_qb_degeneracy.py
    results/common_epoch_sensitivity.json        -- compute_common_epoch.py
    (no input file needed for sigma_Qb -- it is analytical from the
     K_d/Q_b degeneracy, with the published Q_b envelopes hard-coded
     below from Langseth (1976), Saito (2007), and Nagihara (2018).)

Output schema (kd_error_budget.json):
    {
      "A15": {
        "sigma_stat": float,         # bootstrap CI half-width
        "sigma_Qb":   float,         # K_d * (max(Q_b)-min(Q_b)) / (2*Q_b_nom)
        "sigma_zb":   float,         # half-range over the borestem-cut sweep
        "sigma_thr":  float,         # half-range over stability-threshold sweep
        "sigma_epoch": float,        # |common-1974 refit - certified| (one-sided)
        "sigma_A":    float,         # half-range of K_d* over the in-situ albedo band
        "sigma_chi":  float,         # Hayne 2017 chi sensitivity (constant)
        "sigma_H":    float,         # joint K_d-H fit sensitivity
        "sigma_Ks":   float,         # surface conductivity (constant)
        "sigma_rho":  float,         # bulk density (constant)
        "total_quadrature": float,   # sqrt(sum sigma_i^2)
        "median":  float,            # bootstrap median (mW/m/K)
        "ci95_lo": float,            # 95% lower bound (mW/m/K)
        "ci95_hi": float             # 95% upper bound (mW/m/K)
      },
      "A17": { ... same keys ... },
      "albedo_contrast": {           # K_d*(A17) - K_d*(A15) under the albedo (not summed)
        "common_albedo": [...],       # both sites at the same constant A
        "common_albedo_min_contrast": float,
        "band_most_adverse": float    # A17 band minimum - A15 band maximum
      }
    }

Run with:
    python pipeline/compute/compute_error_budget.py
"""
from __future__ import annotations
import json
import pathlib

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "results"

# Published Q_b envelopes in mW m^-2 (Langseth 1976 / Saito 2007 / Nagihara 2018).
# The nominal comes from config.SITES (single source of truth; the hardcoded
# 16 here once went stale at 15 -- the 2026-06-30 straggler); only the
# literature envelope bounds are stated locally.
from lunar.config import SITES as _SITES
QB_ENVELOPES = {
    "A15": {"nominal": _SITES["A15"]["Q_BASAL"] * 1e3, "low": 14.0, "high": 25.0},
    "A17": {"nominal": _SITES["A17"]["Q_BASAL"] * 1e3, "low": 10.0, "high": 18.0},
}

# Fixed-input sensitivities (chi, H, K_s, rho) are re-retrievals at the
# perturbed inputs, generated by
# compute_fixed_input_sensitivities.py -> fixed_input_sensitivities.json.
# Run that script first if the file is missing.


ALB_BIAS_MAX_K = 1.0   # level criterion for the in-situ albedo band [K]
ALB_TS_TOL_K = 5.0     # Keihm et al. (1973a,b) surface-mean uncertainty [K]
_ADOPTED_ALBEDO = {s: _SITES[s]["albedo"] for s in ("A15", "A17")}


def _half_range(values):
    """Half-range = (max - min) / 2 across a sensitivity sweep."""
    v = np.asarray(values, dtype=float)
    return float((v.max() - v.min()) / 2.0)


def main() -> int:
    print("Loading inputs...")
    kd = json.loads((OUT / "kd_retrieval_results.json").read_text())
    bs = json.loads((OUT / "borestem_sensitivity.json").read_text())
    th = json.loads((OUT / "stability_threshold_sensitivity.json").read_text())
    sb = json.loads((OUT / "surface_bias_test.json").read_text())
    alb = json.loads((OUT / "albedo_sensitivity.json").read_text())["cases"]
    fx = json.loads((OUT / "fixed_input_sensitivities.json").read_text())
    ce = json.loads((OUT / "common_epoch_sensitivity.json").read_text())

    budget = {}
    for site in ("A15", "A17"):
        bootstrap = kd[site]["bootstrap"]
        # sigma_stat = half-width of the bootstrap 16-84 percentile interval
        samples_mW = np.array(bootstrap["samples"]) * 1e3
        p16, p84 = np.percentile(samples_mW, [16, 84])
        sigma_stat = float((p84 - p16) / 2.0)

        # sigma_Qb from the DIRECT degeneracy map (audit F-9): half-range of
        # the measured K_d*(Q_b) over the published envelope. The old
        # analytical rule K_d*(alpha Qb) = alpha K_d* is a disproved model
        # of the degeneracy -- it UNDERSTATED A15 (whose direct response is
        # steeper than proportional) and even had the A17 direction wrong.
        # results/qb_degeneracy.json is written by compute_qb_degeneracy.py;
        # run it first if missing.
        from scipy.interpolate import PchipInterpolator
        env = QB_ENVELOPES[site]
        kd_nom_mW = kd[site]["kd_star"] * 1e3
        dg = json.loads((OUT / "qb_degeneracy.json").read_text())["sites"][site]
        f_kd = PchipInterpolator([r["qb_mW"] for r in dg],
                                 [r["kd_star_mW"] for r in dg])
        qq = np.linspace(env["low"], env["high"], 200)
        kd_env = f_kd(qq)
        sigma_Qb = float((kd_env.max() - kd_env.min()) / 2.0)
        qb_asym = (float(kd_env.max() - kd_nom_mW),
                   float(kd_env.min() - kd_nom_mW))   # (+up, -down) vs nominal

        # Sweep half-ranges.
        # sigma_zb uses only the physically defensible cuts {70, 80, 90} cm.
        # The 60-cm cut readmits a borestem-contaminated sensor at A17
        # (manuscript Sec. 3.2) and is a diagnostic, not an uncertainty.
        cuts = bs["cut_cm"]
        zb_vals = [v for c, v in zip(cuts, bs[site]) if c >= 70]
        sigma_zb = _half_range(zb_vals)
        sigma_thr = _half_range(th[site]["kd_star_mW"])
        # sigma_A over the +/-0.01 Bond-albedo envelope (the published
        # Vasavada 2012 lat-band scatter). Perturbations beyond ~0.01
        # push the deep-T(K_d) response into a non-monotonic regime
        # where the retrieval hops between RMSE branches, so larger
        # envelopes do not define a meaningful 1-sigma.
        dA = np.asarray(sb["delta_albedo"], dtype=float)
        kA = np.asarray(sb[site]["kd_star"], dtype=float)
        sigma_A_pm001 = _half_range(kA[np.abs(dA) <= 0.0101])   # old +-0.01 row (report)
        # sigma_A over the IN-SITU ALBEDO BAND (audit 2026-10-04). The constant
        # albedo is an effective, level-setting parameter (no published site
        # value fits). Two in-situ data sets bound it: the meter-scale sensor
        # LEVEL (the fitted column may not run warm or cold by more than
        # ALB_BIAS_MAX_K, the scale of the per-sensor residual scatter) and the
        # diurnal-mean SURFACE temperature measured at each site (Keihm et al.
        # 1973a,b via Hayne et al. 2017 Table A2, +-5 K), which excludes the
        # high-K_d solutions that higher albedos would need.
        band = sorted((c for c in alb
                       if c["site"] == site and c["family"] == "constant"
                       and abs(c["bias_K"]) <= ALB_BIAS_MAX_K
                       and abs(c["surface_mean_K"] - c["surface_mean_obs_K"]) <= ALB_TS_TOL_K
                       and not c["at_grid_edge"]), key=lambda c: c["A"])
        kd_band = [c["kd_star_mW"] for c in band]
        sigma_A = _half_range(kd_band)
        albedo_band = dict(albedo_min=band[0]["A"], albedo_max=band[-1]["A"],
                           albedos=[c["A"] for c in band], kd_star_mW=kd_band,
                           kd_min_mW=min(kd_band), kd_max_mW=max(kd_band),
                           asym_up_down=(float(max(kd_band) - kd[site]["kd_star"] * 1e3),
                                         float(min(kd_band) - kd[site]["kd_star"] * 1e3)),
                           adopted_albedo_inside=bool(band[0]["A"] <= _ADOPTED_ALBEDO[site] <= band[-1]["A"]))

        # Solver systematic: grid+dt convergence (halve dz0 to 1 mm @ 4% growth
        # and halve dt to 1800 s -> <=0.025) combined in quadrature with the
        # anchor-depth sensitivity (the converged K_d* spans 0.06 mW across
        # z0 = 0.45-0.70 m -> half-range ~0.03): sqrt(0.025^2 + 0.03^2) ~ 0.04.
        # NOTE the inner spin-up is now CONVERGED (EQ_N_INNER=90, flux closure
        # <0.5%); the old n_inner=12 biased K_d* HIGH by ~0.4 mW, but that was a
        # BIAS (now removed), NOT a 1-sigma. The reported K_d* sits within this
        # sigma of the closure->0 limit. Source: n_inner + z0 studies 2026-06-30.
        sigma_solver = 0.04

        # sigma_epoch: the A17 stability windows mix 1974-1977 epochs
        # aligned with depth; re-fitting every sensor at one shared 1974
        # window moves K_d* by this much (one-sided; manuscript
        # Sec. "consistency"). A15 is epoch-uniform already (<0.02).
        sigma_epoch = abs(ce[site]["common_1974"]["kd_star_mW"]
                          - ce[site]["certified"]["kd_star_mW"])

        # Quadrature total covers the statistical and measured-input
        # components that respond linearly across their envelopes.
        # chi and H are NOT totaled: they parameterize the Hayne
        # functional form itself, and re-retrieving at the Vasavada
        # chi = 1.48 normalisation drives the minimum outside the
        # physical sweep range at both sites -- K_d* is reported
        # conditional on the published form (chi = 2.7, H = 6 cm),
        # exactly as it is conditional on the published Q_b. Their
        # ranges are reported separately as conditionality terms.
        sigmas = {
            "sigma_stat": sigma_stat,
            "sigma_solver": sigma_solver,
            "sigma_Qb": sigma_Qb,
            "sigma_zb": sigma_zb,
            "sigma_thr": sigma_thr,
            "sigma_epoch": sigma_epoch,
            "sigma_A": sigma_A,
            "sigma_Ks": float(fx[site]["sigma_Ks"]),
            "sigma_rho": float(fx[site]["sigma_rho"]),
        }
        total = float(np.sqrt(sum(s ** 2 for s in sigmas.values())))
        sigmas["sigma_Qb_asymmetric_up_down"] = qb_asym   # not summed (report)
        sigmas["sigma_A_band"] = albedo_band               # not summed (report)
        sigmas["sigma_A_pm001_previous"] = sigma_A_pm001   # not summed (report)
        sigmas["conditional_chi"] = float(fx[site]["sigma_chi"])
        sigmas["conditional_H"] = float(fx[site]["sigma_H"])
        sigmas["kd_at_chi_1p48"] = float(fx[site]["kd_at_chi_1p48"])

        budget[site] = {
            **sigmas,
            "total_quadrature": total,
            "median": float(np.median(samples_mW)),
            "ci95_lo": float(np.percentile(samples_mW, 2.5)),
            "ci95_hi": float(np.percentile(samples_mW, 97.5)),
        }

        print(f"\n  {site}:")
        for k, v in budget[site].items():
            print(f"    {k:<20} = {v}" if isinstance(v, (tuple, list, dict))
                  else f"    {k:<20} = {v:.4f}")

    # Inter-site contrast under the albedo (reported, not summed). Two cases:
    # a COMMON albedo error (both sites shifted to the same constant A) and
    # INDEPENDENT errors within each site's in-situ band (most adverse pairing).
    const = {(c["site"], round(c["A"], 4)): c for c in alb
             if c["family"] == "constant" and not c["at_grid_edge"]}
    common = [dict(A=A, kd_A15=const[("A15", A)]["kd_star_mW"], kd_A17=const[("A17", A)]["kd_star_mW"],
                   contrast=const[("A17", A)]["kd_star_mW"] - const[("A15", A)]["kd_star_mW"])
              for (s, A) in sorted(const) if s == "A15" and ("A17", A) in const]
    b15, b17 = budget["A15"]["sigma_A_band"], budget["A17"]["sigma_A_band"]
    budget["albedo_contrast"] = dict(
        common_albedo=common,
        common_albedo_min_contrast=min(r["contrast"] for r in common),
        band_most_adverse=b17["kd_min_mW"] - b15["kd_max_mW"])
    print(f"\n  albedo contrast: common-A minimum {budget['albedo_contrast']['common_albedo_min_contrast']:+.2f}"
          f" over A={common[0]['A']}-{common[-1]['A']}; band most adverse "
          f"{budget['albedo_contrast']['band_most_adverse']:+.2f} mW/m/K")

    out_path = OUT / "kd_error_budget.json"
    out_path.write_text(json.dumps(budget, indent=2))
    print(f"\nSaved: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
